# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 28) do

  create_table "bundles", :force => true do |t|
    t.column "name",           :string
    t.column "user_id",        :integer
    t.column "clustertype_id", :integer
    t.column "body",           :text
    t.column "collection_id",  :integer
  end

  create_table "bundletypes", :force => true do |t|
    t.column "name",    :string
    t.column "ordered", :integer
  end

  create_table "clusters_keywords", :id => false, :force => true do |t|
    t.column "cluster_id", :integer
    t.column "keyword_id", :integer
  end

  create_table "clusters_users", :id => false, :force => true do |t|
    t.column "cluster_id", :integer
    t.column "user_id",    :integer
  end

  create_table "collections", :force => true do |t|
    t.column "user_id",     :integer
    t.column "name",        :string
    t.column "description", :text
    t.column "status",      :string,  :limit => 20
  end

  create_table "collections_users", :force => true do |t|
    t.column "collection_id", :integer
    t.column "user_id",       :integer
    t.column "status",        :integer
  end

  create_table "helptexts", :force => true do |t|
    t.column "name",    :string
    t.column "body",    :text
    t.column "user_id", :integer
  end

  create_table "keywords_nodes", :id => false, :force => true do |t|
    t.column "node_id",    :integer
    t.column "keyword_id", :integer
  end

  create_table "keywords_people", :force => true do |t|
    t.column "person_id",  :integer
    t.column "keyword_id", :integer
  end

  create_table "keywords_recordings", :force => true do |t|
    t.column "recording_id", :integer
    t.column "keyword_id",   :integer
  end

  create_table "marks_tags", :force => true do |t|
    t.column "tag_id",    :integer
    t.column "mark_type", :string,  :limit => 20
    t.column "mark_id",   :integer
  end

  create_table "members_superbundles", :force => true do |t|
    t.column "superbundle_id", :integer
    t.column "member_id",      :integer
    t.column "member_type",    :string,  :limit => 20
  end

  create_table "nodes", :force => true do |t|
    t.column "name",           :string
    t.column "synopsis",       :text
    t.column "notes",          :text
    t.column "body",           :text
    t.column "person_id",      :integer
    t.column "user_id",        :integer
    t.column "source_id",      :integer
    t.column "status",         :string
    t.column "rating",         :integer
    t.column "image",          :string
    t.column "clip",           :string
    t.column "playfrom",       :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "playto",         :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "keywords_count", :integer
  end

  create_table "nodes_people", :force => true do |t|
    t.column "person_id", :integer
    t.column "node_id",   :integer
  end

  create_table "offenders_warnings", :force => true do |t|
    t.column "warning_id",    :integer
    t.column "offender_type", :string,  :limit => 20
    t.column "offender_id",   :integer
  end

  create_table "paddies_users", :force => true do |t|
    t.column "user_id",    :integer
    t.column "paddy_id",   :integer
    t.column "paddy_type", :string,  :limit => 20
  end

  create_table "people", :force => true do |t|
    t.column "name",          :string
    t.column "image",         :string
    t.column "description",   :text
    t.column "notes",         :text
    t.column "node_count",    :integer
    t.column "collection_id", :integer
  end

  create_table "people_sources", :force => true do |t|
    t.column "person_id", :integer
    t.column "source_id", :integer
  end

  create_table "scraps_scratchpads", :force => true do |t|
    t.column "scratchpad_id", :integer
    t.column "scrap_type",    :string,  :limit => 20
    t.column "scrap_id",      :integer
    t.column "position",      :integer
  end

  create_table "scratchpads", :force => true do |t|
    t.column "name",    :string
    t.column "user_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "sources", :force => true do |t|
    t.column "name",          :string
    t.column "notes",         :text
    t.column "synopsis",      :text
    t.column "person_id",     :integer
    t.column "user_id",       :integer
    t.column "body",          :text
    t.column "clip",          :string
    t.column "duration",      :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "rating",        :integer
    t.column "collection_id", :integer
  end

  create_table "tags", :force => true do |t|
    t.column "parent_id",      :integer
    t.column "name",           :string
    t.column "description",    :text
    t.column "colour",         :string,  :limit => 7
    t.column "nodes",          :integer
    t.column "keywords_count", :integer
    t.column "user_id",        :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",           :string,   :limit => 80, :default => "", :null => false
    t.column "salted_password", :string,   :limit => 40, :default => "", :null => false
    t.column "email",           :string,   :limit => 60, :default => "", :null => false
    t.column "diminutive",      :string,   :limit => 40
    t.column "firstname",       :string,   :limit => 40
    t.column "lastname",        :string,   :limit => 40
    t.column "salt",            :string,   :limit => 40, :default => "", :null => false
    t.column "verified",        :integer,                :default => 0
    t.column "role",            :string,   :limit => 40
    t.column "security_token",  :string,   :limit => 40
    t.column "token_expiry",    :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "logged_in_at",    :datetime
    t.column "deleted",         :integer,                :default => 0
    t.column "delete_after",    :datetime
  end

  create_table "warnings", :force => true do |t|
    t.column "body",           :text
    t.column "offender_type",  :string,  :limit => 20
    t.column "offender_id",    :integer
    t.column "user_id",        :integer
    t.column "warningtype_id", :string
  end

  create_table "warningtypes", :force => true do |t|
    t.column "name",         :string
    t.column "prevents_use", :integer
  end

end
